version: 2.1

orbs:
  android: circleci/android@3.1.0

commands:
  setup-bazel:
    description: |
      Setup the Bazel build system used for building Android projects
    parameters:
      bazel-version:
        type: string
        default: "bazel"
    steps:
      - run:
          name: Add Bazel Apt repository
          command: |
            sudo apt install curl gnupg
            curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
            sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
      - run:
          name: Install Bazel from Apt
          command: | 
            sudo apt update && sudo apt install << parameters.bazel-version >>

jobs:
  unit-test:
    parameters:
      bazel-version:
        description: "Pinned Bazel version"
        default: "bazel-8.2.1"
        type: string
    executor:
      name: android/android_docker
      tag: 2025.03.1
    steps:
      - checkout
      - android/accept_licenses
      - setup-bazel:
          bazel-version: <<parameters.bazel-version>>
      - run:
          name: Run tests
          command: << parameters.bazel-version >> test //src/test:all
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/bazel-testlogs/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  build:
    parameters:
      bazel-version:
        description: "Pinned Bazel version"
        default: "bazel-8.2.1"
        type: string
    executor:
      name: android/android_docker
      tag: 2025.03.1
    steps:
      - checkout
      - android/accept_licenses
      - setup-bazel:
          bazel-version: <<parameters.bazel-version>>
      - run:
          name: Run build
          command: << parameters.bazel-version >> build //src/main:app
      - store_artifacts:
          path: ~/project/bazel-bin/src/main/app.apk
      - store_artifacts:
          path: ~/project/bazel-bin/src/main/app_unsigned.apk

workflows:
  test-and-build:
    jobs:
      - unit-test
      - build:
          requires:
            - unit-test
